/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xlednickym@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package led_projekt

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type LedTreatmentListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateTreatment - Create new treatment
   CreateTreatment(ctx *gin.Context)

    // DeleteTreatment - Deletes specific treatment
   DeleteTreatment(ctx *gin.Context)

    // GetTreatmentDetail - Provides details about treatment
   GetTreatmentDetail(ctx *gin.Context)

    // GetTreatments - Provides the list of all treatments
   GetTreatments(ctx *gin.Context)

    // UpdateTreatment - Updates specific treatment
   UpdateTreatment(ctx *gin.Context)

 }

// partial implementation of LedTreatmentListAPI - all functions must be implemented in add on files
type implLedTreatmentListAPI struct {

}

func newLedTreatmentListAPI() LedTreatmentListAPI {
  return &implLedTreatmentListAPI{}
}

func (this *implLedTreatmentListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/treatments", this.CreateTreatment)
  routerGroup.Handle( http.MethodDelete, "/treatments/:treatmentId", this.DeleteTreatment)
  routerGroup.Handle( http.MethodGet, "/treatments/:treatmentId", this.GetTreatmentDetail)
  routerGroup.Handle( http.MethodGet, "/treatments", this.GetTreatments)
  routerGroup.Handle( http.MethodPut, "/treatments/:treatmentId", this.UpdateTreatment)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateTreatment - Create new treatment
// func (this *implLedTreatmentListAPI) CreateTreatment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteTreatment - Deletes specific treatment
// func (this *implLedTreatmentListAPI) DeleteTreatment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetTreatmentDetail - Provides details about treatment
// func (this *implLedTreatmentListAPI) GetTreatmentDetail(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetTreatments - Provides the list of all treatments
// func (this *implLedTreatmentListAPI) GetTreatments(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateTreatment - Updates specific treatment
// func (this *implLedTreatmentListAPI) UpdateTreatment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

