/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xlednickym@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package led_projekt

import (
	"time"
)

type Treatment struct {

	// Unique id of treatment
	Id string `json:"id"`

	// Name of patient
	Name string `json:"name,omitempty"`

	// Unique identifier of the patient known to Web-In-Cloud system
	PatientId string `json:"patientId"`

	// Timestamp when the treatment started
	StartDate time.Time `json:"startDate,omitempty"`

	// Timestamp when the treatment will end
	EndDate time.Time `json:"endDate,omitempty"`
}
