/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xlednickym@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package led_projekt

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newLedTreatmentListAPI()
    api.addRoutes(group)
  }
  
}